spring:
  datasource:
    username: testuser # 위에서 설정한 사용자 정보 입니다.
    password: testpass # 위에서 설정한 사용자 정보 입니다.
    url: jdbc:postgresql://localhost:5432/testdb # jdbc url을 설정합니다. 위에서 생성한 testdb를 사용합니다.
    driver-class-name: org.postgresql.Driver # postgreSQL 드라이버를 사용합니다.
  h2.console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace # 로그 레벨 설정 추가